### ISSUE TITLE
Would you please release your data interface to the Airlines dataset?

### ISSUE THREAD

**Issue by hikaru-nara** [yftah89/PBLM-Domain-Adaptation#1]
We want to develop your work and run tests on the Airlines dataset for our research publication. Could you please release your code for the data interface to the Airlines dataset?

**Comment by yftah89** [comment]
Hi Hikaru, thank you for your interest in my research :)
I don't currently have the code, but it should be easy to write.
Just make sure that the splits are balanced and use the rest of the dataset as an unlabeled data for PBLM.
The data can be found here - https://github.com/quankiquanki/skytrax-reviews-dataset
The pre-processing remains the same, so you can use the rest of the code as-is. 
Good luck :)

**Comment by hikaru-nara** [comment]
Thanks, I've just finished writing the interface.
